name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.4", "8"]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpcs, composer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: php-actions/composer@v5

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src tests

      - name: Run phpcs
        run: phpcs -q --report=checkstyle src

     # - name: Run PHPUnit
       # run: vendor/bin/phpunit
